version: '3.7'

services:

  rails:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      - MYSQL_HOSTNAME=$MYSQL_HOSTNAME
      - RAILS_DB=$RAILS_DB
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

  mysql:
    image: percona
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD